// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdK-CRTJFs-9HX9x-hP-PPFpIxO3oW84',
    appId: '1:878176063962:web:755a0b21b04be5cd6e30e3',
    messagingSenderId: '878176063962',
    projectId: 'deardiary2-31023',
    authDomain: 'deardiary2-31023.firebaseapp.com',
    storageBucket: 'deardiary2-31023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqSg5j79yVAYjk0ppSZrBvvJV_jNueBk',
    appId: '1:878176063962:android:8a039302716bf3786e30e3',
    messagingSenderId: '878176063962',
    projectId: 'deardiary2-31023',
    storageBucket: 'deardiary2-31023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPIhyKZpI5x_fPdC08olkeVU9lsY6sBmw',
    appId: '1:878176063962:ios:f31563d55f2c3a6c6e30e3',
    messagingSenderId: '878176063962',
    projectId: 'deardiary2-31023',
    storageBucket: 'deardiary2-31023.appspot.com',
    iosBundleId: 'com.example.deardiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPIhyKZpI5x_fPdC08olkeVU9lsY6sBmw',
    appId: '1:878176063962:ios:a04f5671ebc6cc516e30e3',
    messagingSenderId: '878176063962',
    projectId: 'deardiary2-31023',
    storageBucket: 'deardiary2-31023.appspot.com',
    iosBundleId: 'com.example.deardiary.RunnerTests',
  );
}
